name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout código
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Instalar dependências do sistema
      run: |
        sudo apt update
        sudo apt install -y python3-pip zip unzip openjdk-11-jdk wget
        pip install buildozer cython

    - name: Baixar Android command line tools
      run: |
        mkdir -p $HOME/android-sdk/cmdline-tools
        cd $HOME/android-sdk/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip
        mv cmdline-tools latest
        export PATH=$HOME/android-sdk/cmdline-tools/latest/bin:$PATH
        yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses

     - name: Install required SDKs and tools
       run: |
        mkdir -p $HOME/android-sdk/cmdline-tools
        cd $HOME/android-sdk/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip
        mv cmdline-tools latest
        export PATH=$HOME/android-sdk/cmdline-tools/latest/bin:$PATH
        yes | sdkmanager --licenses
        yes | sdkmanager "build-tools;34.0.0" "platform-tools" "platforms;android-31" "platforms;android-34"

        # Ensure PATH includes the correct build-tools and platform-tools
        echo "export PATH=$HOME/android-sdk/build-tools/34.0.0:$HOME/android-sdk/platform-tools:$PATH" >> $GITHUB_ENV

        # Verify aidl is installed
        if ! [ -f "$HOME/android-sdk/build-tools/34.0.0/aidl" ]; then
          echo "Error: aidl not found. Please check build-tools installation." && exit 1
        fi

    - name: Configurar variáveis do SDK
      run: |
        echo "export ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
        echo "export PATH=$HOME/android-sdk/platform-tools:$HOME/android-sdk/cmdline-tools/latest/bin:$PATH" >> $GITHUB_ENV

    - name: Compilar APK com Buildozer
      run: |
        buildozer android debug

    - name: Renomear e mover APK para release
      run: |
        mkdir -p release
        cp bin/*.apk release/OpenAirApp.apk

    - name: Criar release no GitHub
      uses: softprops/action-gh-release@v1
      with:
        name: OpenAirApp
        tag_name: v1.0.${{ github.run_number }}
        files: release/OpenAirApp.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
