name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout código
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Instalar dependências do sistema e Android
      run: |
        sudo apt update
        sudo apt install -y python3-pip zip unzip openjdk-11-jdk adb zipalign
        pip install buildozer cython

    - name: Inicializar e compilar APK com Buildozer
      run: |
        buildozer android debug

    - name: Renomear e mover APK para release
      run: |
        mkdir -p release
        cp bin/*.apk release/OpenAirApp.apk

    - name: Criar release no GitHub
      uses: softprops/action-gh-release@v1
      with:
        name: OpenAirApp
        tag_name: v1.0.${{ github.run_number }}
        files: release/OpenAirApp.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
